name: MCUtils
version: '1.0-SNAPSHOT'
main: com.github.silvertreekr.mcutils.MCUtils
api-version: '1.21'
authors: [ SilverTreeKR ]
dependencies:
  server:
    HeadDatabase:
      load: BEFORE
      required: true
      join-classpath: true
    MCPrefixAchievement:
      load: BEFORE
      required: true
      join-classpath: true